baseURL: https://phill93.de/
languageCode: de-de
title: Phill's Homepage
theme: "PaperMod"
enableGitInfo: false


params:
    defaultTheme: auto
    profileMode:
        enabled: true
        title: "Phill's Homepage"
        subtitle: "Willkommen auf meiner Homepage"
        imageUrl: "/logo.jpg"
        imageTitle: "This is my icon"
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Services
              url: "https://phill93.net"

    socialIcons:
        - name: "github"
          url: "https://github.com/Phill93"
        - name: "pgpkey"
          url: "https://phill93.de/gpg.pub.asc"
