baseURL: https://phill93.de/
languageCode: de-de
title: Phill's Homepage
theme: "PaperMod"
enableGitInfo: false


params:
    defaultTheme: auto
    profileMode:
        enabled: true
        title: "Phill's Homepage"
        subtitle: "Willkommen auf meiner Homepage"
        imageUrl: "/logo.jpg"
        imageTitle: "This is my icon"
        imageWidth: 120
        imageHeight: 120

    socialIcons:
        - name: "github"
          url: "https://github.com/Phill93"
        - name: "pgpkey"
          url: "https://phill93.de/gpg.pub.asc"
        - name: "mastodon"
          url: "phill93@phill93.de"

module:
  mounts:
    - source: .well-known
      target: static/.well-known